### PR TITLE
removed custom httpinterceptor implementation as its not required wit…

### PR DESCRIPTION
**Pull request by NilsWild**
…h new HttpClient

removed unused http interceptor implementation

https://github.com/jhipster/generator-jhipster/issues/6281

### CODE REVIEW

**Comment by deepu105** [comment]
I haven't looked at the new HttpClient, does it support interceptors out of the box?

**Comment by NilsWild** [comment]
Yes you only have to register them as providers like so:
providers: [
    { provide: HTTP_INTERCEPTORS, useClass: MyInterceptor, multi: true }
  ],

see: https://github.com/NilsWild/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/_app.module.ts

**Comment by sendilkumarn** [comment]
yeah you dont need them anymore.
I will take a look at both the PRs over the weekend. 

@NilsWild you need to pass on the dependencies too 😎😎😎

**Comment by deepu105** [comment]
We can merge this after merging https://github.com/jhipster/generator-jhipster/issues/6281

**Pull request merged**
