### PR TITLE
rename fontawesome sort icon

### PR DESCRIPTION
**Pull request by maznag**
PR to fix sort icon names for fontawesome v5

related issue jhipster/generator-jhipster#7516

### CODE REVIEW

**Comment by ksilz** [comment]
I'm using 5.0.0-beta.1, and I still have the wrong icons for sorting columns. Shouldn't this be fixed through this pull request?

**Comment by gmarziou** [comment]
@ksilz  5.0.0-beta.1 references ng-jhipster 0.4.5 (check your project's package.json), this pull request was merged in 0.4.7. So it's normal that you don't have it.

**Comment by ctamisier** [comment]
I tried with ng-jhipster 0.5.4 but it doesn't work.
There is still some work to do here, for example about `sortIconSelector? = 'span.fa';`
Now it's `fa-icon` in the master branch of generator-jhipster codebase

**Comment by gmarziou** [comment]
Either use master branch or wait for next v5 release.

**Pull request merged**
