### PR TITLE
Upgrade angular and associated library dependencies

### PR DESCRIPTION
**Pull request by vishal423**

### CODE REVIEW

**Comment by vishal423** [comment]
@pascalgrimaud, After code merge, can you please publish a new version?

**Comment by pascalgrimaud** [comment]
@vishal423 : if you feel confident enough, yes, go ahead and merge it. I can do a release of ng jhipster tomorrow so we can have Angular 10 in next release

**Comment by vishal423** [comment]
@pascalgrimaud, Let's merge over here, and we can track it in the main generator.

**Comment by pascalgrimaud** [comment]
@vishal423 : I'm going to release ng-jhipster in few minutes, but waiting your 'go'. Is it ok for you ?

**Comment by vishal423** [comment]
yes @pascalgrimaud, please do new minor release

**Comment by pascalgrimaud** [comment]
@vishal423 : a new version of ng-jhipster 0.14.0 has been released !

**Comment by vishal423** [comment]
thanks @pascalgrimaud

**Pull request merged**
