### PR TITLE
Ng2 translations in webpack bundles

### PR DESCRIPTION
**Pull request by flaviencathala**
No http requests to load translations anymore, the translation files are now loaded with the app.

### CODE REVIEW

**Comment by deepu105** [comment]
There was a reason to do it with http request instead of bundling it with the source. In a real world apl the translation files will keep growing and if you have multiple languages you will have a lot of json files. So if we bundle it we are making the initial file huge and takes time to download hence loading them as partials will not hit the initial loading. What I would rather do is to improve the partial loader to have some sort of in memory caching so that same file for a language is not requested again. Im not ok to bundle everything in a huge file

**Comment by flaviencathala** [comment]
I agree this is not good at all if the translation files are too big. I will work on a memory caching solution.

**Comment by deepu105** [comment]
@jdubois @gmarziou I gave it some thoughts and I'm still not sure if we should bundle everything. So i'll let you guys decide this.

@flaviencathala if we are bundling then the solution should be different and the we dont need a partial loader at all as it doesnt make sense. So I would rather merge all json files and bundle it at compile time and use a simple loader to load file by language at runtime rather then loading files at runtime

**Comment by gmarziou** [comment]
I'm in favor of bundling everything as it's simpler.
Later on, we could decide to have a bundle per language and have default language in main bundle.

The only thing I haven't tested is in dev when you change one string in one i18n file, is it slower to refresh because of bundling or do we benefit from HMR here as well.

**Comment by jdubois** [comment]
I'm also in favor of bundling everything:

- With Angular 1 that was our main performance issue on the client side, as we kept downloading the JSON files, and I'm really happy to get rid of it
- From the tests done by @gmarziou the size impact is really small, so that's no big deal

**Comment by gzsombor** [comment]
What about this issue? I would be very happy, if every translation could be merged during the build. Do we need something else to implement for it ? I'm not a pro in webpack build magic, that's why I'm asking it 😄

**Comment by deepu105** [comment]
@gzsombor this needs some rework in the ng-jhipster library. 
1 option is: The current translate partial loader needs to be changed to load the merged single file and then load only required portion of the file into memory. 
2 option is: The current translate partial loader needs to be changed to load the merged single file and then we need to remove all the calls in the components to load the file and just use the single loaded file from memory

**Comment by deepu105** [comment]
this PR is not required anymore as the i18n part was revamped

**Pull request closed without merging**
