### PR TITLE
Fix protractor waiting for alerts.

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/11766.

### CODE REVIEW

**Comment by mshima** [comment]
@pascalgrimaud is there an easy way to try ng-jhipster?
I tried
```
cd ng-jhipster
npm run build
cd ../app
npm install ../ng-jhipster/dist
```
But it didn't worked.
```
ERROR in /Users/mshima/git/ng-jhipster/dist/fesm2015/ng-jhipster.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/Users/mshima/git/ng-jhipster/dist/fesm2015/ng-jhipster.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: ../ng-jhipster/dist/fesm2015/ng-jhipster.js.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)
```

**Comment by pascalgrimaud** [comment]
It is always a pain to test this...

Did you try npm link ?
- in ng-jhipster: npm link
- in a generated project: npm link ng-jhipster

Otherwise:
- npm run build
- copy manually to generated project, into node_modules/

I don't remember well if I manage to test it properly

**Comment by mshima** [comment]
> It is always a pain to test this...
> 
> Did you try npm link ?
> 
> * in ng-jhipster: npm link
> * in a generated project: npm link ng-jhipster

Don't work.

> Otherwise:
> 
> * npm run build
> * copy manually to generated project, into node_modules/
> 
> I don't remember well if I manage to test it properly

I used the README instructions, but it's not reproducible on a CI workflow.
I will have to be tested manually then.

**Comment by pascalgrimaud** [comment]
@mshima : ok, tell me if you want to merge this + release

**Comment by mshima** [comment]
> @mshima : ok, tell me if you want to merge this + release

I wanted to test directly in https://github.com/jhipster/generator-jhipster/pull/12403
I will try locally, and ping you afterwards.

**Comment by mshima** [comment]
> @mshima : ok, tell me if you want to merge this + release

@pascalgrimaud tested locally, it worked.
Fell free to do it.

**Pull request merged**
