### PR TITLE
fix: update sort icon

### PR DESCRIPTION
**Pull request by vishal423**
closes: https://github.com/jhipster/generator-jhipster/issues/8105

- An alternative approach to correctly set the sort icons (ascending, descending etc).
- Unit tests to assert different flows

### CODE REVIEW

**Comment by deepu105** [comment]
@wmarques could you follow it up?

**Comment by vishal423** [comment]
@deepu105, @wmarques, did you get chance to look into this PR?

**Comment by vishal423** [comment]
Ping @deepu105 @wmarques

**Comment by wmarques** [comment]
LGTM, just fix the package-lock conflict by rerunning `npm install` and we're good, thanks !

**Comment by vishal423** [comment]
@wmarques , If changes looks good, then, post merge, pls create new release so that original issue can be resolved

**Comment by wmarques** [comment]
@vishal423 Sorry you have again conflicts on the package-lock and package.json files :( I'll merge this once you rebased master !

**Comment by vishal423** [comment]
@wmarques, I have fixed conflicts and also corrected the angular peer dependencies to point to v7.

**Comment by vishal423** [comment]
@wmarques, please create new release so that changes can be included in main project

**Comment by deepu105** [comment]
@wmarques i'm doing a release now. My release scripts in package.json is failing since the package.json inside dist created by ng-packagr will still have the old version and `npm version minor` command will have no effect on it. For now i'll do this manually but can you take a look at this please

**Comment by wmarques** [comment]
@deepu105 oh sorry didn't check this ! Sure I'll look into it. Thanks for doing the release

**Comment by vishal423** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/6527

**Comment by jdubois** [comment]
Thanks @vishal423 !! As this was done during our special "bug bounty booster" event, that qualifies for $200 indeed - is that correct @wmarques @deepu105 ? (I'm sorry I didn't follow up)

**Comment by vishal423** [comment]
Thanks everyone for this awesome project

**Pull request merged**
