### PR TITLE
Bump angular dependencies

### PR DESCRIPTION
**Pull request by vishal423**
Bump angular and associated library dependencies to their latest supported version.

### CODE REVIEW

**Comment by wmarques** [comment]
@deepu105 Can you make a release of the lib so we can test Angular 8 on both the lib and a generated app ?

**Comment by pascalgrimaud** [comment]
@wmarques : I can do it, if needed

**Comment by wmarques** [comment]
@pascalgrimaud yes please go ahead :)

**Comment by pascalgrimaud** [comment]
@wmarques : done, v0.10.0 just released ! Tell me if it works fine for you plz

**Pull request merged**
