### PR TITLE
Upgrade to Angular 6 and RxJS 6

### PR DESCRIPTION
**Pull request by paddya**
I upgraded the dependencies to Angular 6 and RxJS 6.

I also removed the `package-lock.json` file, because it does not seem to be in use anymore. It is only touched for version bumps of the `ng-jhipster` package.

* Used `rxjs-tslint` to move to `.pipe()` and fix all the import paths 
* Added `fullTemplateTypeCheck: true` to fix "Function calls are not supported in decorators [...]"
* Fixed the tests for JhiLanguageService
* Removed package-lock.json

### CODE REVIEW

**Comment by jdubois** [comment]
I'd keep `package-lock.json` in case we switch back to NPM, but that's really minor - thanks a lot for this, it's a much needed contribution!

**Comment by paddya** [comment]
I forgot that `tslint` errors can fail the build. I have now committed the fixes.

**Comment by paddya** [comment]
@jdubois I can add an updated `package-lock.json`. Should I commit it?

**Comment by jdubois** [comment]
Yes, let's not do two different things in the same PR, so we can revert easily if needed

**Comment by paddya** [comment]
I also added the new dependency injection mechanism (`providedIn`) to all services.

**Comment by sendilkumarn** [comment]
Okay, can you also do a release of this version and then I will create a PR?

**Comment by deepu105** [comment]
I'm doing a release

Thanks & Regards,
Deepu

**Pull request merged**
